# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# kubespray-installer test Vagrantfile

$num_instances = 3

# Script to format/mount vda volume for ceph testing
# https://www.vagrantup.com/docs/provisioning/shell.html
$vdisk_setup  = <<-EOF
echo "Formatting and mounting /dev/vda, vdb on /mnt/ceph and /mnt/local"
parted -s /dev/vda mklabel gpt
parted -s /dev/vdb mklabel gpt
parted -s /dev/vda mkpart ext4 16 100%
parted -s /dev/vdb mkpart ext4 16 100%
mkfs.ext4 -q -F /dev/vda1
mkfs.ext4 -q -F /dev/vdb1

mkdir -p /mnt/ceph
mkdir -p /mnt/local
echo "/dev/vda1 /mnt/ceph/ ext4 defaults 0 0" | sudo tee -a /etc/fstab
echo "/dev/vdb1 /mnt/local/ ext4 defaults 0 0" | sudo tee -a /etc/fstab
mount /mnt/ceph
mount /mnt/local
EOF

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"

  (1..$num_instances).each do |i|
    config.vm.define vm_name = "k8s-%02d" % i do |config|
      config.vm.hostname = vm_name

       config.vm.provider :libvirt do |lv|
         lv.memory = 16384
         lv.cpus = 8
         lv.nested = true
         # additional disk for ceph storage, shows up as `vd[a-b]` in the VM
         lv.storage :file, :size => '20G'
         lv.storage :file, :size => '20G'
       end

       config.vm.provision "shell", inline: "swapoff -a"
       config.vm.provision "shell", inline: $vdisk_setup

       ip = "10.90.0.#{i+100}"
       config.vm.network :private_network, ip: ip

     end
  end
end

