# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# kubespray-installer test Vagrantfile

$num_instances = 3

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"

  (1..$num_instances).each do |i|
    config.vm.define vm_name = "k8s-%02d" % i do |config|
      config.vm.hostname = vm_name

       config.vm.provider :libvirt do |lv|
         lv.memory = 16384
         lv.cpus = 8
         lv.machine_virtual_size = 50
         lv.nested = true
       end

       config.vm.provision "shell", inline: "swapoff -a"

       ip = "10.90.0.#{i+100}"
       config.vm.network :private_network, ip: ip

     end
  end
end

